name: Meu primeiro pipeline

on:
  push:
    branches: ["main"]

jobs:
  oi:
    runs-on: ubuntu-latest
    steps:
      - name: Dizer oi
        run: echo "OlÃ¡, Gabriel! Seu pipeline tÃ¡ funcionando ğŸ‰"
